theme: minima
title: Cakebot
name: Cakebot
description: An amazing in development yet high quality Discord bot!
github_username: cakebotpro
markdown: kramdown
email: me@rdil.rocks
plugins:
  - jemoji
  - jekyll-admin
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-gist
  - jekyll-seo-tag
permalink: /:title
title_separator: "-"
repository: cakebotpro/cakebot
show_excerpts: true
timezone: America/New_York
encoding: UTF-8
locale: "en"
url: https://cakebot.club
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .gitignore
