theme: minima
title: Cakebot
name: Cakebot
description: An amazing in development yet high quality Discord bot!
github_username: RDIL
markdown: kramdown
email: cakebot@rdil.rocks
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-admin
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-gist
permalink: /:title:output_ext
title_separator: "-"
repository: RDIL/cakebot
show_excerpts: true
rss: rss
timezone: America/New_York
encoding: UTF-8
locale: "en"
url: https://cakebot.club
twitter_username: Cakebotpro
