name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn|${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        env:
          GIT_USER: RDILBot
        run: yarn deploy
