name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Configure git identity
        run: git config --global user.name "RDILBot" && git config --global user.email "support@rdil.rocks"
      - name: Yarn cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn|${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Pre-build cleanup
        run: yarn gh-pages-clean
      - name: Build
        run: yarn build
      - name: Commit and Push
        run: git remote set-url origin https://RDIL:${PUSH_TOKEN}@github.com/cakebotpro/cakebotpro.github.io.git && yarn gh-pages
